<script setup lang="ts">
import { computed, nextTick, onMounted, onUnmounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { api } from '../api'
import type { VoiceAnalysisJob } from '../types'

const route = useRoute(); const job = ref<VoiceAnalysisJob | null>(null); const error = ref(''); let ws: WebSocket | undefined; let timer: number | undefined
const summaryOpen=ref(true), suggestionsOpen=ref(true), samplesOpen=ref(true); const summaryPage=ref(1), suggestionPage=ref(1), samplePage=ref(1)
const summarySize=ref(6), suggestionSize=ref(10), sampleSize=ref(10); const providerFilter=ref(''), modelFilter=ref(''), voiceFilter=ref(''); const currentSampleId=ref(''); const audioUrl=ref(''); const audio=ref<HTMLAudioElement>()
const terminal=(s:string)=>['completed','failed','canceled'].includes(s); const score=(v:unknown)=>typeof v==='number'?`${Math.round(v*100)}%`:'—'; const matchScore=(v:any)=>score(typeof v==='number'?v:v?.overall)
const profileText=(s:any)=>{const p=s?.normalized_result?.observed_profile;if(typeof p==='string')return p;if(p?.timbre?.length)return p.timbre.join('、');return s?.normalized_result?.evidence||'暂无'}
const samples=computed(()=>job.value?.samples||[])
const sampleValue=(s:any,key:string)=>key==='provider'?s.voice_provider||'未知 Provider':key==='model'?s.voice_model||s.catalog_snapshot?.model||'未知模型':s.voice_key||''
const options=(key:string)=>Array.from(new Set(samples.value.map(s=>sampleValue(s,key)))).filter(Boolean).sort()
const filteredSamples=computed(()=>samples.value.filter(s=>(!providerFilter.value||sampleValue(s,'provider').toLowerCase().includes(providerFilter.value.toLowerCase()))&&(!modelFilter.value||sampleValue(s,'model').toLowerCase().includes(modelFilter.value.toLowerCase()))&&(!voiceFilter.value||sampleValue(s,'voice').toLowerCase().includes(voiceFilter.value.toLowerCase()))))
const pageItems=(items:any[],page:number,size:number)=>size===0?items:items.slice((page-1)*size,page*size); const pages=(count:number,size:number)=>size===0?1:Math.max(1,Math.ceil(count/size))
const visibleSummaries=computed(()=>pageItems(job.value?.voice_summaries||[],summaryPage.value,summarySize.value)); const suggestionGroups=computed(()=>{const groups:any[]=[];const map=new Map();for(const item of job.value?.suggestions||[]){if(!map.has(item.voice_key)){const group={voice_key:item.voice_key,items:[] as any[]};map.set(item.voice_key,group);groups.push(group)}map.get(item.voice_key).items.push(item)}return groups}); const visibleSuggestionGroups=computed(()=>pageItems(suggestionGroups.value,suggestionPage.value,suggestionSize.value)); const visibleSamples=computed(()=>pageItems(filteredSamples.value,samplePage.value,sampleSize.value))
function resetSamplePage(){samplePage.value=1}; function clearFilters(){providerFilter.value='';modelFilter.value='';voiceFilter.value='';resetSamplePage()}
function setPage(kind:'summary'|'suggestion'|'sample',value:number){if(kind==='summary')summaryPage.value=value;if(kind==='suggestion')suggestionPage.value=value;if(kind==='sample')samplePage.value=value}
function showSize(value:string,kind:'summary'|'suggestion'|'sample'){const n=Number(value);if(kind==='summary'){summarySize.value=n;summaryPage.value=1}if(kind==='suggestion'){suggestionSize.value=n;suggestionPage.value=1}if(kind==='sample'){sampleSize.value=n;samplePage.value=1}}
async function viewSamples(summary:any){const [provider,voice]=String(summary.voice_key||'').split(':'); providerFilter.value=provider||'';voiceFilter.value=summary.voice_key||'';const first=samples.value.find(s=>s.voice_key===summary.voice_key);modelFilter.value=first?sampleValue(first,'model'):'';samplesOpen.value=true;samplePage.value=1;await nextTick();document.querySelector('.analysis-samples')?.scrollIntoView({behavior:'smooth',block:'start'})}
async function playSample(sample:any){currentSampleId.value=sample.sample_id;audioUrl.value=`/api/voice-analysis/jobs/${encodeURIComponent(String(route.params.id))}/samples/${encodeURIComponent(sample.sample_id)}/audio`;await nextTick();try{await audio.value?.play()}catch(e:any){error.value=e.message||'音频播放失败'}}
async function load(){try{job.value=await api.voiceAnalysisJob(String(route.params.id))}catch(e:any){error.value=e.message}}
async function review(s:any,status:'approved'|'rejected'){try{const id=String(route.params.id);const result=status==='approved'?await api.approveVoiceAnalysisSuggestion(id,s.suggestion_id):await api.rejectVoiceAnalysisSuggestion(id,s.suggestion_id);s.status=result.status}catch(e:any){error.value=e.message}}
function connect(){ws=new WebSocket(`${location.origin.replace(/^http/,'ws')}/ws/voice-analysis`);ws.onopen=()=>ws?.send(JSON.stringify({type:'subscribe',job_ids:[route.params.id]}));ws.onmessage=e=>{const x=JSON.parse(e.data);if(x.job_id)job.value={...job.value,...x} as VoiceAnalysisJob};ws.onclose=()=>{if(!job.value||!terminal(job.value.status))timer=window.setTimeout(connect,3000)}}
onMounted(async()=>{await load();connect()});onUnmounted(()=>{ws?.close();if(timer)clearTimeout(timer)})
</script>

<template><section class="analysis-detail-page"><router-link to="/voice-analysis" class="back-link">← 返回任务列表</router-link><div v-if="job" class="analysis-header"><div><p class="eyebrow">后台分析任务</p><h1>音色分析详情</h1><p class="analysis-job-id">{{job.job_id}}</p></div><span class="status-pill" :class="`status-${job.status}`">{{job.status}}</span></div><div v-if="job" class="analysis-progress panel"><div class="section-heading"><h2>分析进度</h2><span>{{job.phase}}</span></div><div class="progress-track"><div class="progress-fill" :style="{width:(job.total?Math.round(job.completed/job.total*100):0)+'%'}"></div></div><div class="progress-meta"><span>{{job.completed}} / {{job.total||'待扫描'}} 个样本完成</span><span>失败 {{job.failed}} · 跳过 {{job.skipped}}</span></div></div>
<div v-if="job?.voice_summaries?.length" class="analysis-section"><button class="collapse-heading" @click="summaryOpen=!summaryOpen"><span>{{summaryOpen?'▾':'▸'}} 音色级汇总</span><small>{{job.voice_summaries.length}} 个音色</small></button><div v-if="summaryOpen"><div class="section-tools"><span>第 {{summaryPage}} / {{pages(job.voice_summaries.length,summarySize)}} 页</span><label>每页 <select :value="summarySize" @change="showSize(($event.target as HTMLSelectElement).value,'summary')"><option value="6">6</option><option value="12">12</option><option value="24">24</option><option value="0">全部</option></select></label><button v-if="summarySize!==0&&summaryPage>1" @click="setPage('summary',summaryPage-1)">上一页</button><button v-if="summarySize!==0&&summaryPage<pages(job.voice_summaries.length,summarySize)" @click="setPage('summary',summaryPage+1)">下一页</button></div><div class="summary-grid"><article v-for="summary in visibleSummaries" :key="summary.voice_key" class="summary-card"><div class="summary-card-title"><div class="voice-hover"><h3 tabindex="0">{{summary.voice_key}}</h3><div class="voice-popover"><b>音色库声明</b><p>{{summary.catalog_snapshot?.description||'暂无声明描述'}}</p><small>{{summary.catalog_snapshot?.gender||'未知'}} · {{summary.catalog_snapshot?.age||'未知'}} · {{summary.catalog_snapshot?.category||'未分类'}}</small></div></div><span>{{summary.sample_count}} 个样本</span></div><div class="score-grid"><div><strong>{{matchScore(summary.normalized_result?.catalog_match)}}</strong><small>声明匹配度</small></div><div><strong>{{matchScore(summary.normalized_result?.role_match)}}</strong><small>角色匹配度</small></div></div><p class="feature-line"><span>实际特征</span>{{profileText(summary)}}</p><div v-if="summary.normalized_result?.additional_traits?.length" class="discovery-block"><span>声明之外的新发现</span><div class="discovery-tags"><i v-for="trait in summary.normalized_result.additional_traits" :key="trait">{{trait}}</i></div></div><div v-if="summary.normalized_result?.catalog_enrichment" class="discovery-block"><span>音色库完善建议</span><p v-if="summary.normalized_result.catalog_enrichment.recommended_description">{{summary.normalized_result.catalog_enrichment.recommended_description}}</p><small v-if="summary.normalized_result.catalog_enrichment.missing_from_catalog?.length">声明缺失：{{summary.normalized_result.catalog_enrichment.missing_from_catalog.join("、")}}</small></div><div v-if="summary.normalized_result?.role_match?.mismatches?.length" class="mismatch-block"><span>角色不匹配点</span><ul><li v-for="item in summary.normalized_result.role_match.mismatches" :key="item">{{item}}</li></ul></div><p class="summary-evidence">{{summary.normalized_result?.catalog_match?.details||summary.normalized_result?.role_match?.details||summary.normalized_result?.evidence||"暂无补充说明"}}</p><button class="link-button" @click="viewSamples(summary)">查看该音色样本 →</button></article></div></div></div>
<div class="analysis-section"><button class="collapse-heading" @click="suggestionsOpen=!suggestionsOpen"><span>{{suggestionsOpen?'▾':'▸'}} 建议修改清单</span><small>{{suggestionGroups.length}} 个音色 · {{job?.suggestions?.length||0}} 条建议</small></button><div v-if="suggestionsOpen&&suggestionGroups.length"><div class="section-tools"><span>第 {{suggestionPage}} / {{pages(suggestionGroups.length,suggestionSize)}} 页</span><label>每页 <select :value="suggestionSize" @change="showSize(($event.target as HTMLSelectElement).value,'suggestion')"><option value="10">10</option><option value="20">20</option><option value="50">50</option><option value="0">全部</option></select></label><button v-if="suggestionSize!==0&&suggestionPage>1" @click="setPage('suggestion',suggestionPage-1)">上一页</button><button v-if="suggestionSize!==0&&suggestionPage<pages(suggestionGroups.length,suggestionSize)" @click="setPage('suggestion',suggestionPage+1)">下一页</button></div><div class="suggestion-list"><article v-for="group in visibleSuggestionGroups" :key="group.voice_key" class="suggestion-group"><div class="suggestion-group-title"><strong>{{group.voice_key}}</strong><span>{{group.items.length}} 条建议</span><button class="link-button" @click="viewSamples({voice_key:group.voice_key})">查看样本 →</button></div><div v-for="item in group.items" :key="item.suggestion_id" class="suggestion-row"><div><span class="suggestion-category">{{item.category==='catalog'?'音色库完善':item.category==='role_mismatch'?'角色不匹配':item.category==='performance'?'音色表现调整':'使用场景建议'}}</span><p>{{item.text}}</p></div><div class="suggestion-actions"><span class="suggestion-status">{{item.status}}</span><template v-if="item.status==='pending'"><button class="review-button" @click="review(item,'approved')">采纳</button><button class="review-button muted" @click="review(item,'rejected')">忽略</button></template></div></div></article></div></div><p v-else-if="suggestionsOpen" class="empty-section">暂无建议</p></div>
<div class="analysis-section analysis-samples"><button class="collapse-heading" @click="samplesOpen=!samplesOpen"><span>{{samplesOpen?'▾':'▸'}} 样本分析</span><small>{{filteredSamples.length}} / {{samples?.length||0}} 条</small></button><div v-if="samplesOpen"><div class="filter-bar"><label>Provider<input list="provider-options" v-model="providerFilter" placeholder="全部或输入筛选"><datalist id="provider-options"><option value=""></option><option v-for="item in options('provider')" :key="item" :value="item"></option></datalist></label><label>模型<input list="model-options" v-model="modelFilter" placeholder="全部或输入筛选"><datalist id="model-options"><option value=""></option><option v-for="item in options('model')" :key="item" :value="item"></option></datalist></label><label>音色<input list="voice-options" v-model="voiceFilter" placeholder="全部或输入筛选"><datalist id="voice-options"><option value=""></option><option v-for="item in options('voice')" :key="item" :value="item"></option></datalist></label><button class="clear-filter" @click="clearFilters">清除筛选</button></div><div class="section-tools"><span>第 {{samplePage}} / {{pages(filteredSamples.length,sampleSize)}} 页</span><label>每页 <select :value="sampleSize" @change="showSize(($event.target as HTMLSelectElement).value,'sample')"><option value="10">10</option><option value="20">20</option><option value="50">50</option><option value="100">100</option><option value="0">全部</option></select></label><button v-if="sampleSize!==0&&samplePage>1" @click="setPage('sample',samplePage-1)">上一页</button><button v-if="sampleSize!==0&&samplePage<pages(filteredSamples.length,sampleSize)" @click="setPage('sample',samplePage+1)">下一页</button></div><div v-if="audioUrl" class="analysis-player"><span>当前播放：{{currentSampleId}}</span><audio ref="audio" controls :src="audioUrl"></audio></div><div class="sample-list"><article v-for="sample in visibleSamples" :key="sample.sample_id" class="sample-row"><div class="sample-main"><div class="sample-title"><button class="play-button" :class="{playing:currentSampleId===sample.sample_id}" @click="playSample(sample)">{{currentSampleId===sample.sample_id?'▶':'▷'}}</button><strong>{{sample.voice_name||sample.voice_id}}</strong><span>{{sample.result?.status||'待处理'}}</span></div><small>{{sample.voice_provider}} · {{sample.voice_model||sample.catalog_snapshot?.model||'未知模型'}} · {{sample.character_name||'未知角色'}}</small><small>{{sample.story_id}} · {{sample.text}}</small></div><div v-if="sample.result?.normalized_result" class="sample-tags"><span>{{sample.result.normalized_result.observed_gender}}</span><span>{{sample.result.normalized_result.observed_age}}</span><span>{{sample.result.normalized_result.timbre?.join('、')}}</span></div><p v-if="sample.result?.normalized_result?.evidence" class="sample-evidence">{{sample.result.normalized_result.evidence}}</p></article></div><p v-if="!visibleSamples.length" class="empty-section">没有符合条件的样本</p></div></div><p v-if="error" class="error">{{error}}</p></section></template>
